"""Machine-local configuration and dependency diagnostics for SEEKER."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
import shutil
import sys
import tempfile
from typing import Callable, Mapping

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 fallback
    import tomli as tomllib  # type: ignore[no-redef]


CONFIG_ENV = "SEEKER_CONFIG"
ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class LocalConfig:
    xtb: str = ""
    gaussian: str = ""

    def as_dict(self) -> dict[str, str]:
        return {
            "xtb": self.xtb,
            "gaussian": self.gaussian,
        }


@dataclass(frozen=True)
class Diagnostic:
    name: str
    status: str
    detail: str


def config_path(environ: Mapping[str, str] | None = None) -> Path:
    environment = os.environ if environ is None else environ
    configured = environment.get(CONFIG_ENV, "").strip()
    if configured:
        return Path(configured).expanduser()
    if (ROOT / "pyproject.toml").is_file():
        return ROOT / ".seeker.local.toml"
    config_root = environment.get("XDG_CONFIG_HOME", "").strip()
    base = Path(config_root).expanduser() if config_root else Path.home() / ".config"
    return base / "seeker" / "config.toml"


def load_config(path: Path | None = None) -> LocalConfig:
    target = config_path() if path is None else Path(path)
    if not target.is_file():
        return LocalConfig()
    with target.open("rb") as handle:
        payload = tomllib.load(handle)
    tools = payload.get("tools", {})
    if not isinstance(tools, dict):
        raise ValueError(f"invalid [tools] table in {target}")
    return LocalConfig(
        xtb=str(tools.get("xtb", "")).strip(),
        gaussian=str(tools.get("gaussian", "")).strip(),
    )


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_config(config: LocalConfig, path: Path | None = None) -> Path:
    target = (config_path() if path is None else Path(path)).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Machine-local SEEKER tool paths. Generated by `seeker configure`.",
        "[tools]",
        f"xtb = {_toml_string(config.xtb)}",
        f"gaussian = {_toml_string(config.gaussian)}",
        "",
    ]
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=target.name + ".", suffix=".tmp", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines))
        os.replace(temporary, target)
    finally:
        if temporary.exists():
            temporary.unlink()
    return target


def _resolve_executable(value: str) -> str:
    if not value:
        return ""
    expanded = Path(value).expanduser()
    if expanded.parent != Path(".") or os.sep in value:
        return str(expanded.resolve()) if expanded.is_file() else ""
    located = shutil.which(value)
    return str(Path(located).resolve()) if located else ""


def resolve_tools(
    config: LocalConfig | None = None,
    environ: Mapping[str, str] | None = None,
) -> LocalConfig:
    """Resolve tools with environment > config > PATH precedence."""

    environment = os.environ if environ is None else environ
    local = load_config() if config is None else config
    xtb_value = environment.get("XTB_COMMAND", "").strip() or local.xtb or "xtb"
    gaussian_value = environment.get("GAUSSIAN_COMMAND", "").strip() or local.gaussian
    if not gaussian_value:
        gaussian_value = "g16" if shutil.which("g16") else "gdv"
    return LocalConfig(
        xtb=_resolve_executable(xtb_value),
        gaussian=_resolve_executable(gaussian_value),
    )


def diagnostics(config: LocalConfig | None = None) -> tuple[Diagnostic, ...]:
    resolved = resolve_tools(config)
    python_status = "ok" if sys.version_info >= (3, 10) else "error"
    items = [
        Diagnostic(
            "python",
            python_status,
            f"{sys.executable} ({sys.version.split()[0]}; requires >=3.10)",
        ),
        Diagnostic(
            "xtb",
            "ok" if resolved.xtb else "optional",
            resolved.xtb or "not configured; required for the xTB backend",
        ),
        Diagnostic(
            "Gaussian",
            "ok" if resolved.gaussian else "optional",
            resolved.gaussian
            or "not configured; required for B3LYP post-processing",
        ),
    ]
    try:
        import sklearn  # noqa: F401

        discovery = Diagnostic("discovery extra", "ok", "scikit-learn available")
    except ImportError:
        discovery = Diagnostic(
            "discovery extra", "optional", "install seeker-conformer[discovery]"
        )
    items.append(discovery)
    return tuple(items)


def _prompt_tool(
    label: str,
    current: str,
    validator: Callable[[str], str],
    input_fn: Callable[[str], str],
    output_fn: Callable[[str], None],
) -> str:
    explanations = {
        "xTB executable": "Executable used for xTB energies and final geometry optimizations.",
        "Gaussian executable": "g16 or gdv executable used for B3LYP single points and optimizations.",
    }
    while True:
        suffix = f" [{current}]" if current else " [skip]"
        output_fn(f"{label}{suffix}")
        hint = (
            f"  {explanations.get(label, 'Path to the external tool on this machine.')} "
            "Enter a path, press Enter to accept the detected value, or enter '-' to skip."
        )
        dim = (
            bool(getattr(sys.stdout, "isatty", lambda: False)())
            and "NO_COLOR" not in os.environ
            and os.environ.get("TERM", "") != "dumb"
        )
        output_fn(f"\x1b[2;38;5;245m{hint}\x1b[0m" if dim else hint)
        answer = input_fn("> ").strip()
        if answer.lower() in {"-", "none", "skip"}:
            return ""
        value = answer or current
        if not value:
            return ""
        validated = validator(value)
        if validated:
            return validated
        output_fn(f"Not found or invalid: {value}")


def configure_interactively(
    path: Path | None = None,
    *,
    input_fn: Callable[[str], str] = input,
    output_fn: Callable[[str], None] = print,
) -> LocalConfig:
    target = config_path() if path is None else Path(path)
    current = load_config(target)
    detected = resolve_tools(current)
    output_fn("Configure machine-local tools. Press Enter to accept; enter '-' to skip.")
    xtb = _prompt_tool(
        "xTB executable",
        current.xtb or detected.xtb,
        _resolve_executable,
        input_fn,
        output_fn,
    )
    gaussian = _prompt_tool(
        "Gaussian executable",
        current.gaussian or detected.gaussian,
        _resolve_executable,
        input_fn,
        output_fn,
    )

    configured = LocalConfig(
        xtb=xtb,
        gaussian=gaussian,
    )
    output_fn(f"Saved local configuration: {write_config(configured, target)}")
    return configured
