"""Dependency-free ANSI terminal UI for SEEKER evolution runs."""

from __future__ import annotations

import argparse
import math
import os
import select
import shutil
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import IO, Any, Callable, Mapping, Sequence

from .geometry import build_bond_graph
from .models import GenerationStats, Individual, Molecule


ESC = "\x1b["
RESET = f"{ESC}0m"
COLORS = {
    "sand": f"{ESC}38;5;180m",
    "dim_sand": f"{ESC}38;5;137m",
    "water": f"{ESC}38;5;31m",
    "cyan": f"{ESC}38;5;51m",
    "green": f"{ESC}38;5;82m",
    "yellow": f"{ESC}38;5;220m",
    "orange": f"{ESC}38;5;208m",
    "white": f"{ESC}38;5;255m",
    "muted": f"{ESC}38;5;245m",
    "red": f"{ESC}38;5;203m",
}
SPARKS = "▁▂▃▄▅▆▇█"
MOLECULE_SUPERSAMPLE = 4

ATOM_RGB = {
    "H": (225, 228, 235),
    "C": (152, 158, 170),
    "N": (42, 112, 245),
    "O": (238, 55, 50),
    "F": (70, 205, 85),
    "P": (245, 145, 45),
    "S": (238, 205, 45),
    "CL": (55, 190, 75),
    "BR": (155, 68, 45),
    "I": (125, 70, 170),
}

ATOMIC_MASSES = {
    "H": 1.008,
    "C": 12.011,
    "N": 14.007,
    "O": 15.999,
    "F": 18.998,
    "P": 30.974,
    "S": 32.06,
    "CL": 35.45,
    "BR": 79.904,
    "I": 126.904,
}


def _supports_ansi(stream: IO[str]) -> bool:
    return (
        bool(getattr(stream, "isatty", lambda: False)())
        and os.environ.get("TERM") != "dumb"
        and "NO_COLOR" not in os.environ
    )


def keycap(label: str, *, ansi: bool = True) -> str:
    """Render one documented key consistently, with a plain-text fallback."""

    plain = f"[{label}]"
    if not ansi:
        return plain
    return f"{COLORS['yellow']}{ESC}1m{plain}{RESET}"


def dashboard_controls(
    mode: str,
    *,
    selected: int = 0,
    count: int = 0,
    compact: bool = False,
    ansi: bool = True,
) -> str:
    """Return the always-visible control legend for a dashboard mode."""

    m = keycap("m", ansi=ansi)
    digits = keycap("1-9", ansi=ansi)
    n = keycap("n", ansi=ansi)
    p = keycap("p", ansi=ansi)
    if mode == "focus":
        return f"ISLAND {selected + 1}/{count}  {m} close  {n}/{p} change"
    if mode == "overview":
        prefix = "ALL ISLANDS  " if compact else ""
        return f"{prefix}{m} show previews  {digits} focus"
    prefix = "ALL PREVIEWS  " if compact else ""
    return f"{prefix}{m} compact islands  {digits} focus"


def _visible_len(value: str) -> int:
    """Return a useful display width for strings generated by this module."""

    import re

    return len(re.sub(r"\x1b\[[0-9;]*m", "", value))


def _fit(value: str, width: int) -> str:
    if width <= 0:
        return ""
    plain_width = _visible_len(value)
    if plain_width <= width:
        return value + " " * (width - plain_width)
    # Dashboard labels are ASCII, so slicing before an ANSI reset is safe here.
    plain = value
    import re

    plain = re.sub(r"\x1b\[[0-9;]*m", "", plain)
    return plain[: max(0, width - 1)] + "…"


def sparkline(values: Sequence[float], width: int = 24) -> str:
    """Render a compact, scale-independent Unicode graph."""

    finite = [float(value) for value in values if math.isfinite(float(value))]
    if not finite:
        return "·" * max(1, width)
    selected = finite[-max(1, width) :]
    low, high = min(selected), max(selected)
    if math.isclose(low, high, rel_tol=1.0e-12, abs_tol=1.0e-15):
        return SPARKS[len(SPARKS) // 2] * len(selected)
    return "".join(
        SPARKS[min(len(SPARKS) - 1, int((value - low) / (high - low) * (len(SPARKS) - 1)))]
        for value in selected
    )


def vertical_chart(
    values: Sequence[float],
    width: int = 24,
    height: int = 3,
) -> list[str]:
    """Render a compact bottom-filled chart over several terminal rows."""

    width = max(1, int(width))
    height = max(1, int(height))
    finite = [float(value) for value in values if math.isfinite(float(value))]
    if not finite:
        return ["·" * width for _ in range(height)]
    selected = finite[-width:]
    low, high = min(selected), max(selected)
    if math.isclose(low, high, rel_tol=1.0e-12, abs_tol=1.0e-15):
        levels = [max(1, height * 4) for _value in selected]
    else:
        levels = [
            max(1, round((value - low) / (high - low) * (height * 8 - 1)) + 1)
            for value in selected
        ]
    rows: list[str] = []
    for row in reversed(range(height)):
        cells: list[str] = []
        for level in levels:
            fill = level - row * 8
            if fill <= 0:
                cells.append(" ")
            elif fill >= 8:
                cells.append("█")
            else:
                cells.append(SPARKS[fill - 1])
        rows.append("".join(cells).ljust(width))
    return rows


def _format_metric(value: float) -> str:
    if not math.isfinite(value):
        return "n/a"
    magnitude = abs(value)
    if magnitude >= 10000 or (magnitude and magnitude < 0.001):
        return f"{value:.3e}"
    return f"{value:.5f}"


def balanced_compromise(
    population: Sequence[Individual],
    objective_names: Sequence[str],
) -> tuple[Individual | None, float]:
    """Return the Pareto member closest to the normalized ideal point.

    Every objective exposed to the engine is a minimization fitness.  Min-max
    normalization keeps an energy measured in hartree from numerically
    overwhelming a dimensionless structural score.
    """

    names = tuple(objective_names)
    valid = [
        individual
        for individual in population
        if individual.valid
        and names
        and all(
            math.isfinite(individual.objective_value(name))
            for name in names
        )
    ]
    if not valid:
        return None, float("inf")
    pareto = [individual for individual in valid if individual.rank == 0]
    candidates = pareto or valid
    minima = {
        name: min(individual.objective_value(name) for individual in valid)
        for name in names
    }
    maxima = {
        name: max(individual.objective_value(name) for individual in valid)
        for name in names
    }

    def score(individual: Individual) -> float:
        regrets: list[float] = []
        for name in names:
            span = maxima[name] - minima[name]
            regrets.append(
                0.0
                if math.isclose(span, 0.0, rel_tol=1.0e-12, abs_tol=1.0e-15)
                else (individual.objective_value(name) - minima[name]) / span
            )
        return math.sqrt(sum(value * value for value in regrets) / len(regrets))

    best = min(candidates, key=lambda item: (score(item), item.id))
    return best, score(best)


def _dot(first: Sequence[float], second: Sequence[float]) -> float:
    return sum(float(left) * float(right) for left, right in zip(first, second))


def _cross(first: Sequence[float], second: Sequence[float]) -> tuple[float, float, float]:
    return (
        first[1] * second[2] - first[2] * second[1],
        first[2] * second[0] - first[0] * second[2],
        first[0] * second[1] - first[1] * second[0],
    )


def _normalize(vector: Sequence[float]) -> tuple[float, float, float]:
    norm = math.sqrt(_dot(vector, vector))
    if norm <= 1.0e-14:
        return (1.0, 0.0, 0.0)
    return tuple(float(value) / norm for value in vector)  # type: ignore[return-value]


def _symmetric_eigenframe(
    matrix: Sequence[Sequence[float]],
) -> tuple[tuple[float, tuple[float, float, float]], ...]:
    """Jacobi diagonalization for one real symmetric 3x3 matrix."""

    values = [[float(matrix[row][column]) for column in range(3)] for row in range(3)]
    vectors = [[1.0 if row == column else 0.0 for column in range(3)] for row in range(3)]
    for _iteration in range(32):
        p, q = max(
            ((0, 1), (0, 2), (1, 2)),
            key=lambda pair: abs(values[pair[0]][pair[1]]),
        )
        off_diagonal = values[p][q]
        if abs(off_diagonal) <= 1.0e-13:
            break
        tau = (values[q][q] - values[p][p]) / (2.0 * off_diagonal)
        tangent = (
            1.0 / (tau + math.sqrt(1.0 + tau * tau))
            if tau >= 0.0
            else -1.0 / (-tau + math.sqrt(1.0 + tau * tau))
        )
        cosine = 1.0 / math.sqrt(1.0 + tangent * tangent)
        sine = tangent * cosine
        app, aqq = values[p][p], values[q][q]
        values[p][p] = app - tangent * off_diagonal
        values[q][q] = aqq + tangent * off_diagonal
        values[p][q] = values[q][p] = 0.0
        for index in range(3):
            if index in (p, q):
                continue
            aip, aiq = values[index][p], values[index][q]
            values[index][p] = values[p][index] = cosine * aip - sine * aiq
            values[index][q] = values[q][index] = sine * aip + cosine * aiq
        for index in range(3):
            vip, viq = vectors[index][p], vectors[index][q]
            vectors[index][p] = cosine * vip - sine * viq
            vectors[index][q] = sine * vip + cosine * viq

    result: list[tuple[float, tuple[float, float, float]]] = []
    for column in range(3):
        vector = _normalize(tuple(vectors[row][column] for row in range(3)))
        pivot = max(range(3), key=lambda index: abs(vector[index]))
        if vector[pivot] < 0.0:
            vector = tuple(-value for value in vector)
        result.append((values[column][column], vector))
    return tuple(sorted(result, key=lambda item: item[0], reverse=True))


def _principal_frame(
    molecule: Molecule,
    atom_indices: Sequence[int] | None = None,
) -> tuple[
    tuple[float, float, float],
    tuple[float, float, float],
    tuple[float, float, float],
    tuple[float, float, float],
]:
    """Return center of mass and maximum-dispersion camera axes.

    The first two axes span the face with the largest mass-weighted spatial
    dispersion.  The viewing/depth axis is their right-handed normal and thus
    corresponds to the least-dispersed principal direction.
    """

    selected_atoms = (
        tuple(molecule.atoms[index] for index in atom_indices)
        if atom_indices is not None
        else molecule.atoms
    )
    masses = [ATOMIC_MASSES.get(atom.element.upper(), 12.0) for atom in selected_atoms]
    total_mass = sum(masses)
    center = tuple(
        sum(mass * atom.position[axis] for mass, atom in zip(masses, selected_atoms))
        / total_mass
        for axis in range(3)
    )
    covariance = [[0.0 for _column in range(3)] for _row in range(3)]
    for mass, atom in zip(masses, selected_atoms):
        displacement = tuple(atom.position[axis] - center[axis] for axis in range(3))
        for row in range(3):
            for column in range(3):
                covariance[row][column] += (
                    mass * displacement[row] * displacement[column] / total_mass
                )
    eigenframe = _symmetric_eigenframe(covariance)
    screen_x = eigenframe[0][1]
    screen_y = eigenframe[1][1]
    view = _normalize(_cross(screen_x, screen_y))
    # Stabilize the handedness against tiny numeric changes.
    least_axis = eigenframe[2][1]
    if _dot(view, least_axis) < 0.0:
        screen_y = tuple(-value for value in screen_y)
        view = tuple(-value for value in view)
    return center, screen_x, screen_y, view


def _covalent_components(
    graph: Sequence[Sequence[int]],
) -> tuple[tuple[int, ...], ...]:
    """Return deterministic connected components of a covalent graph."""

    pending = set(range(len(graph)))
    components: list[tuple[int, ...]] = []
    while pending:
        seed = min(pending)
        pending.remove(seed)
        stack = [seed]
        component: list[int] = []
        while stack:
            current = stack.pop()
            component.append(current)
            for neighbour in sorted(graph[current], reverse=True):
                if neighbour in pending:
                    pending.remove(neighbour)
                    stack.append(neighbour)
        components.append(tuple(sorted(component)))
    return tuple(components)


def _camera_reference_component(
    molecule: Molecule,
    graph: Sequence[Sequence[int]],
) -> tuple[int, ...]:
    """Choose the chemically informative fragment used to orient the camera."""

    components = _covalent_components(graph)

    def importance(component: tuple[int, ...]) -> tuple[int, float, int, int]:
        heavy_atoms = sum(
            molecule.atoms[index].element.upper() != "H" for index in component
        )
        mass = sum(
            ATOMIC_MASSES.get(molecule.atoms[index].element.upper(), 12.0)
            for index in component
        )
        return heavy_atoms, mass, len(component), -min(component)

    return max(components, key=importance)


def _blend(color: Sequence[int], intensity: float) -> tuple[int, int, int]:
    factor = min(1.35, max(0.0, float(intensity)))
    return tuple(min(255, max(0, round(channel * factor))) for channel in color)  # type: ignore[return-value]


def render_molecule(
    molecule: Molecule,
    width: int,
    height: int,
    *,
    angle_degrees: float = 0.0,
) -> list[str]:
    """Rasterize an XYZ geometry as a true-color 3D ball-and-stick model.

    Covalent connectivity is inferred once from covalent radii.  The camera is
    oriented by the mass-weighted principal frame of the largest covalent
    fragment, so its most informative face remains legible while the relative
    position of every other fragment is preserved.  Perspective, sphere
    lighting and a per-pixel z-buffer retain the third dimension in a
    terminal-only view.  A 4x supersampled raster is antialiased into solid
    true-color half-block pixels, avoiding the disconnected-dot appearance of
    a Braille renderer.
    """

    width = max(1, int(width))
    height = max(1, int(height))
    if not molecule.atoms:
        return [" " * width for _ in range(height)]
    output_pixel_width, output_pixel_height = width, height * 2
    sample_scale = MOLECULE_SUPERSAMPLE
    pixel_width = output_pixel_width * sample_scale
    pixel_height = output_pixel_height * sample_scale
    graph = build_bond_graph(molecule)
    reference_component = _camera_reference_component(molecule, graph)
    center, screen_x, screen_y, view = _principal_frame(
        molecule,
        reference_component,
    )
    # ``angle_degrees`` is retained for API compatibility and permits a small
    # roll without changing the maximum-dispersion viewing face.
    roll = math.radians(float(angle_degrees))
    rolled_x = tuple(
        math.cos(roll) * screen_x[index] + math.sin(roll) * screen_y[index]
        for index in range(3)
    )
    rolled_y = tuple(
        -math.sin(roll) * screen_x[index] + math.cos(roll) * screen_y[index]
        for index in range(3)
    )
    coordinates: list[tuple[float, float, float]] = []
    for atom in molecule.atoms:
        displacement = tuple(atom.position[index] - center[index] for index in range(3))
        coordinates.append(
            (_dot(displacement, rolled_x), _dot(displacement, rolled_y), _dot(displacement, view))
        )
    spatial_span = max(
        max(values) - min(values) for values in zip(*coordinates)
    )
    camera_distance = max(5.0, spatial_span * 4.5)
    perspective = [
        (
            x * camera_distance / max(1.0e-6, camera_distance - depth),
            y * camera_distance / max(1.0e-6, camera_distance - depth),
            depth,
        )
        for x, y, depth in coordinates
    ]
    xs = [point[0] for point in perspective]
    ys = [point[1] for point in perspective]
    # Choose radii in final solid pixels, then lift them into the supersampled
    # raster.  The ball-to-stick ratio keeps ring topology open and legible.
    output_radius = max(1.8, min(4.5, output_pixel_height / 13.0))
    base_radius = output_radius * sample_scale
    margin = base_radius + 1.5 * sample_scale
    x_span = max(xs) - min(xs)
    y_span = max(ys) - min(ys)
    scale = min(
        (pixel_width - 2.0 * margin) / x_span if x_span > 1.0e-12 else float("inf"),
        (pixel_height - 2.0 * margin) / y_span if y_span > 1.0e-12 else float("inf"),
    )
    if not math.isfinite(scale) or scale <= 0.0:
        scale = 1.0
    mid_x = 0.5 * (min(xs) + max(xs))
    mid_y = 0.5 * (min(ys) + max(ys))
    projected = [
        (
            (x - mid_x) * scale + (pixel_width - 1) / 2.0,
            -(y - mid_y) * scale + (pixel_height - 1) / 2.0,
            depth,
        )
        for x, y, depth in perspective
    ]

    black = (0, 0, 0)
    pixels = [[black for _column in range(pixel_width)] for _row in range(pixel_height)]
    zbuffer = [
        [float("-inf") for _column in range(pixel_width)]
        for _row in range(pixel_height)
    ]

    def paint(column: int, row: int, depth: float, color: tuple[int, int, int]) -> None:
        if (
            0 <= column < pixel_width
            and 0 <= row < pixel_height
            and depth >= zbuffer[row][column]
        ):
            zbuffer[row][column] = depth
            pixels[row][column] = color

    bond_color = (202, 208, 218)
    bond_radius = max(0.50 * sample_scale, base_radius * 0.16)
    for first, neighbours in enumerate(graph):
        for second in neighbours:
            if second <= first:
                continue
            x0, y0, z0 = projected[first]
            x1, y1, z1 = projected[second]
            dx, dy = x1 - x0, y1 - y0
            length_squared = dx * dx + dy * dy
            left = max(0, math.floor(min(x0, x1) - bond_radius - 1.0))
            right = min(pixel_width - 1, math.ceil(max(x0, x1) + bond_radius + 1.0))
            top = max(0, math.floor(min(y0, y1) - bond_radius - 1.0))
            bottom = min(pixel_height - 1, math.ceil(max(y0, y1) + bond_radius + 1.0))
            for row in range(top, bottom + 1):
                for column in range(left, right + 1):
                    if length_squared <= 1.0e-12:
                        fraction = 0.0
                    else:
                        fraction = min(
                            1.0,
                            max(
                                0.0,
                                ((column - x0) * dx + (row - y0) * dy)
                                / length_squared,
                            ),
                        )
                    nearest_x = x0 + fraction * dx
                    nearest_y = y0 + fraction * dy
                    distance = math.hypot(column - nearest_x, row - nearest_y)
                    coverage = min(
                        1.0,
                        max(0.0, bond_radius + 0.55 * sample_scale - distance),
                    )
                    if coverage <= 0.0:
                        continue
                    depth = z0 + fraction * (z1 - z0)
                    shade = 0.52 + 0.38 * coverage + 0.06 * depth / camera_distance
                    paint(column, row, depth, _blend(bond_color, shade))

    light = _normalize((-0.55, 0.65, 1.0))
    for index in sorted(range(len(projected)), key=lambda item: projected[item][2]):
        center_x, center_y, center_depth = projected[index]
        element = molecule.atoms[index].element.upper()
        radius_factor = 0.72 if element == "H" else 1.08 if element in {"O", "S"} else 1.0
        radius = base_radius * radius_factor
        base_color = ATOM_RGB.get(element, (190, 155, 105))
        left = max(0, math.floor(center_x - radius - 1.0))
        right = min(pixel_width - 1, math.ceil(center_x + radius + 1.0))
        top = max(0, math.floor(center_y - radius - 1.0))
        bottom = min(pixel_height - 1, math.ceil(center_y + radius + 1.0))
        for row in range(top, bottom + 1):
            for column in range(left, right + 1):
                nx = (column - center_x) / radius
                ny = -(row - center_y) / radius
                radial_squared = nx * nx + ny * ny
                coverage = min(1.0, max(0.0, 1.45 - math.sqrt(radial_squared)))
                if radial_squared > 1.20 or coverage <= 0.0:
                    continue
                nz = math.sqrt(max(0.0, 1.0 - min(1.0, radial_squared)))
                diffuse = max(0.0, _dot((nx, ny, nz), light))
                specular = max(0.0, diffuse) ** 12
                edge = max(0.0, min(1.0, nz * 1.4))
                intensity = coverage * (0.28 + 0.57 * diffuse + 0.28 * specular) * (
                    0.72 + 0.28 * edge
                )
                surface_depth = center_depth + nz * radius / max(scale, 1.0e-6)
                paint(column, row, surface_depth, _blend(base_color, intensity))

    # Box-filter the high-resolution image.  Averaging true colors produces
    # smooth silhouettes and sticks while retaining the z-buffered occlusion
    # already resolved in the supersampled canvas.
    output_pixels: list[list[tuple[int, int, int]]] = []
    sample_area = sample_scale * sample_scale
    for output_row in range(output_pixel_height):
        downsampled_row: list[tuple[int, int, int]] = []
        source_top = output_row * sample_scale
        for output_column in range(output_pixel_width):
            source_left = output_column * sample_scale
            downsampled_row.append(
                tuple(
                    round(
                        sum(
                            pixels[source_top + sub_row][source_left + sub_column][channel]
                            for sub_row in range(sample_scale)
                            for sub_column in range(sample_scale)
                        )
                        / sample_area
                    )
                    for channel in range(3)
                )
            )
        output_pixels.append(downsampled_row)

    rows: list[str] = []
    for terminal_row in range(height):
        pieces: list[str] = []
        top_pixels = output_pixels[2 * terminal_row]
        bottom_pixels = output_pixels[2 * terminal_row + 1]
        for top_color, bottom_color in zip(top_pixels, bottom_pixels):
            if top_color == black and bottom_color == black:
                pieces.append(" ")
            else:
                pieces.append(
                    f"{ESC}38;2;{top_color[0]};{top_color[1]};{top_color[2]}m"
                    f"{ESC}48;2;{bottom_color[0]};{bottom_color[1]};{bottom_color[2]}m"
                    f"▀{RESET}"
                )
        rows.append("".join(pieces))
    return rows


def play_intro(
    stream: IO[str] = sys.stdout,
    *,
    frame_delay: float = 0.09,
    enabled: bool | None = None,
) -> None:
    """Walk a molecular, anthropomorphic seeker across rolling dunes."""

    if enabled is None:
        enabled = _supports_ansi(stream) and os.environ.get("SEEKER_ANIMATION", "1") != "0"
    if not enabled:
        return

    width = min(78, max(58, shutil.get_terminal_size((78, 24)).columns))
    scene_height = 12
    seeker_frames = (
        (
            "    ●       ",
            "    │       ",
            " ●──●──●  ╷ ",
            "    ●   ╲●│ ",
            "   ╱ ╲    │ ",
            "  ●   ●   │ ",
        ),
        (
            "    ●       ",
            "    │       ",
            " ●──●──●  ╷ ",
            "    ●   ╲●│ ",
            "    ╲╱    │ ",
            "    ●─●   │ ",
        ),
    )

    def dune_height(x: int) -> int:
        return 9 + round(
            1.35 * math.sin(2.0 * math.pi * x / 29.0)
            + 0.65 * math.sin(2.0 * math.pi * x / 13.0)
        )

    dune_heights = [dune_height(x) for x in range(width)]
    # Draw only on the terminal's alternate screen.  Clearing the primary
    # screen made the first launcher prompt invisible in some macOS terminal
    # configurations even though the shell was correctly waiting for input.
    stream.write(f"{ESC}?1049h{ESC}?25l{ESC}2J{ESC}H")
    try:
        for step in range(24):
            progress = step / 23.0
            frame = seeker_frames[(step // 2) % len(seeker_frames)]
            left_x = 2 + round((width - len(frame[0]) - 4) * progress)
            ground_x = min(width - 1, left_x + 5)
            top_y = dune_heights[ground_x] - len(frame)
            canvas = [[" " for _ in range(width)] for _ in range(scene_height)]
            seeker_cells: set[tuple[int, int]] = set()
            atom_cells: set[tuple[int, int]] = set()
            probe_cells: set[tuple[int, int]] = set()
            for x, ground_y in enumerate(dune_heights):
                previous_y = dune_heights[max(0, x - 1)]
                next_y = dune_heights[min(width - 1, x + 1)]
                canvas[ground_y][x] = (
                    "╱" if next_y < previous_y else "╲" if next_y > previous_y else "─"
                )
                for y in range(ground_y + 1, scene_height):
                    canvas[y][x] = "·" if (x + y) % 3 == 0 else " "
            for sprite_y, row in enumerate(frame):
                for sprite_x, character in enumerate(row):
                    if character == " ":
                        continue
                    target_x = left_x + sprite_x
                    target_y = top_y + sprite_y
                    if 0 <= target_x < width and 0 <= target_y < scene_height:
                        canvas[target_y][target_x] = character
                        cell = (target_x, target_y)
                        seeker_cells.add(cell)
                        if character == "●":
                            atom_cells.add(cell)
                        elif sprite_x >= 10:
                            probe_cells.add(cell)
            lines = [
                "",
                f"{COLORS['sand']}{'S E E K E R':^{width}}{RESET}",
                f"{COLORS['muted']}{'interactive multiobjective search':^{width}}{RESET}",
                "",
            ]
            for y, row in enumerate(canvas):
                rendered_row = []
                active_color = ""
                for x, character in enumerate(row):
                    cell = (x, y)
                    if cell in atom_cells:
                        color = COLORS["yellow"]
                    elif cell in probe_cells:
                        color = COLORS["orange"]
                    elif cell in seeker_cells:
                        color = COLORS["white"]
                    else:
                        color = COLORS["dim_sand"]
                    if color != active_color:
                        rendered_row.append(color)
                        active_color = color
                    rendered_row.append(character)
                lines.append("".join(rendered_row).rstrip() + RESET)
            stream.write(f"{ESC}H" + "\n".join(lines))
            stream.flush()
            time.sleep(max(0.0, frame_delay))
    finally:
        stream.write(f"{ESC}?25h{ESC}?1049l")
        stream.flush()


@dataclass(frozen=True)
class IslandSnapshot:
    index: int
    valid: int
    size: int
    pareto: int
    diversity: float
    fitness: float
    compromise: Individual | None = None
    compromise_score: float = float("inf")


class TerminalDashboard:
    """Full-screen terminal dashboard fed directly by GA generation events."""

    def __init__(
        self,
        generations: int,
        objective_names: Sequence[str],
        output_dir: str | Path,
        *,
        stream: IO[str] = sys.stdout,
        enabled: bool | None = None,
        migration_delay: float = 0.14,
        history_window: int = 20,
        molecule_provider: Callable[[Individual], Molecule] | None = None,
        input_stream: IO[str] | None = None,
        log_path: str | Path | None = None,
    ) -> None:
        if enabled is None:
            enabled = _supports_ansi(stream)
        self.enabled = bool(enabled)
        self.generations = max(0, int(generations))
        self.objective_names = tuple(objective_names)
        self.output_dir = Path(output_dir)
        self.log_path = (
            Path(log_path) if log_path is not None else self.output_dir / "run.log"
        )
        self.stream = stream
        self.input_stream = sys.stdin if input_stream is None else input_stream
        self._use_controlling_terminal_fallback = input_stream is None
        self._owned_input_stream: IO[str] | None = None
        self.migration_delay = migration_delay
        self.history_window = max(2, int(history_window))
        self.molecule_provider = molecule_provider
        self.started = False
        self.closed = False
        self.mutation_history: list[float] = []
        self.crossover_history: list[float] = []
        self.objective_history: dict[str, list[float]] = {
            name: [] for name in self.objective_names
        }
        self._last_lines = 0
        self._draw_lock = threading.RLock()
        self._latest_frame: tuple[
            GenerationStats,
            tuple[tuple[Individual, ...], ...],
            tuple[Mapping[str, Any], ...],
        ] | None = None
        self._molecule_view_open = False
        # None selects the adaptive default: compact map below 100 columns,
        # preview gallery on wider terminals.  A key press makes it explicit.
        self._previews_hidden: bool | None = None
        self._selected_island = 0
        self._input_stop = threading.Event()
        self._input_thread: threading.Thread | None = None
        self._input_fd: int | None = None
        self._saved_terminal_attributes: list[Any] | None = None

    def _snapshots(
        self,
        islands: Sequence[Sequence[Individual]],
        stats: GenerationStats,
    ) -> list[IslandSnapshot]:
        snapshots: list[IslandSnapshot] = []
        for index, population in enumerate(islands):
            valid = [individual for individual in population if individual.valid]
            primary_objective = self.objective_names[0] if self.objective_names else "energy"
            fitness_values = [
                individual.objective_value(primary_objective)
                for individual in valid
                if math.isfinite(individual.objective_value(primary_objective))
            ]
            reported_diversity = (
                stats.island_diversities_deg[index]
                if index < len(stats.island_diversities_deg)
                else self._diversity(valid)
            )
            # Rank is assigned locally by environmental selection on every island.
            compromise, compromise_score = balanced_compromise(
                valid, self.objective_names
            )
            snapshots.append(
                IslandSnapshot(
                    index=index,
                    valid=len(valid),
                    size=len(population),
                    pareto=sum(individual.rank == 0 for individual in valid),
                    diversity=reported_diversity,
                    fitness=min(fitness_values, default=float("inf")),
                    compromise=compromise,
                    compromise_score=compromise_score,
                )
            )
        return snapshots

    def set_molecule_provider(
        self, provider: Callable[[Individual], Molecule] | None
    ) -> None:
        """Attach the engine geometry builder before the first generation."""

        self.molecule_provider = provider

    def handle_key(self, key: str, *, redraw: bool = True) -> bool:
        """Handle one documented dashboard key without blocking the GA."""

        normalized = key.lower()
        with self._draw_lock:
            if self.closed:
                return False
            island_count = (
                len(self._latest_frame[1]) if self._latest_frame is not None else 0
            )
            if normalized == "m":
                if self._molecule_view_open:
                    self._molecule_view_open = False
                    self._previews_hidden = True
                else:
                    width, _height = shutil.get_terminal_size((120, 38))
                    currently_hidden = (
                        self._previews_hidden
                        if self._previews_hidden is not None
                        else width < 100
                    )
                    self._previews_hidden = not currently_hidden
            elif normalized in {"n", "]"} and island_count:
                self._selected_island = (self._selected_island + 1) % island_count
            elif normalized in {"p", "["} and island_count:
                self._selected_island = (self._selected_island - 1) % island_count
            elif normalized.isdigit() and normalized != "0" and island_count:
                requested = int(normalized) - 1
                if requested >= island_count:
                    return False
                self._selected_island = requested
                self._molecule_view_open = True
            else:
                return False
            if redraw and self.started and self._latest_frame is not None:
                stats, islands, migrations = self._latest_frame
                self._draw(stats, islands, migrations)
            return True

    def _start_input_listener(self) -> None:
        if self._input_thread is not None:
            return
        try:
            import termios
            import tty

            input_stream = self.input_stream
            if (
                not getattr(input_stream, "isatty", lambda: False)()
                and self._use_controlling_terminal_fallback
            ):
                # ``run_seeker.sh`` supervises workers as asynchronous shell
                # jobs.  Some shells consequently attach stdin to /dev/null
                # even though the process still owns the controlling terminal.
                # Read keys from that terminal directly so the live dashboard
                # remains interactive through launchers, pipes and loggers.
                self._owned_input_stream = open(
                    "/dev/tty",
                    "r",
                    encoding="utf-8",
                    buffering=1,
                )
                input_stream = self._owned_input_stream
                self.input_stream = input_stream
            if not getattr(input_stream, "isatty", lambda: False)():
                return
            descriptor = input_stream.fileno()
            self._saved_terminal_attributes = termios.tcgetattr(descriptor)
            tty.setcbreak(descriptor)
            self._input_fd = descriptor
        except (AttributeError, OSError, ValueError, ImportError):
            if self._owned_input_stream is not None:
                self._owned_input_stream.close()
                self._owned_input_stream = None
            self._input_fd = None
            self._saved_terminal_attributes = None
            return

        self._input_stop.clear()
        self._input_thread = threading.Thread(
            target=self._input_loop,
            name="seeker-tui-input",
            daemon=True,
        )
        self._input_thread.start()

    def _input_loop(self) -> None:
        descriptor = self._input_fd
        if descriptor is None:
            return
        while not self._input_stop.is_set():
            try:
                readable, _writable, _exceptional = select.select(
                    [descriptor], [], [], 0.10
                )
                if not readable:
                    continue
                payload = os.read(descriptor, 32).decode("utf-8", errors="ignore")
            except OSError:
                break
            for character in payload:
                self.handle_key(character)

    def _stop_input_listener(self) -> None:
        self._input_stop.set()
        thread = self._input_thread
        if thread is not None and thread is not threading.current_thread():
            thread.join(timeout=0.25)
        self._input_thread = None
        descriptor = self._input_fd
        attributes = self._saved_terminal_attributes
        self._input_fd = None
        self._saved_terminal_attributes = None
        if descriptor is not None and attributes is not None:
            try:
                import termios

                termios.tcsetattr(descriptor, termios.TCSADRAIN, attributes)
            except (OSError, ValueError, ImportError):
                pass
        if self._owned_input_stream is not None:
            self._owned_input_stream.close()
            self._owned_input_stream = None

    def _recent_history(self, values: Sequence[float]) -> Sequence[float]:
        return values[-self.history_window :]

    def _enter_screen(self) -> None:
        if self.started:
            return
        self.stream.write(f"{ESC}?1049h{ESC}?25l{ESC}2J{ESC}H")
        self.started = True
        self._start_input_listener()

    def start_waiting(self, message: str) -> None:
        """Open the dashboard before the first generation is available."""

        if not self.enabled or self.closed:
            return
        with self._draw_lock:
            self._enter_screen()
            width, height = shutil.get_terminal_size((120, 38))
            width = max(72, width)
            inner_width = width - 4
            lines = [
                f"{COLORS['sand']}╔{'═' * (width - 2)}╗{RESET}",
                _fit(
                    f"{COLORS['sand']}║{RESET}  SEEKER  "
                    f"{COLORS['muted']}terminal evolutionary observatory{RESET}  "
                    f"{COLORS['cyan']}INITIALIZING GENERATION 0{RESET}",
                    width - 1,
                )
                + f"{COLORS['sand']}║{RESET}",
                f"{COLORS['sand']}╠{'═' * (width - 2)}╣{RESET}",
                "",
                _fit(f"  {COLORS['cyan']}◌{RESET}  {message}", inner_width),
                _fit(
                    f"  {COLORS['muted']}The island dashboard will appear as soon as the initial fitness evaluations finish.{RESET}",
                    inner_width,
                ),
                "",
                f"{COLORS['water']}{'  ≋  ' * max(1, width // 5)}{RESET}"[
                    : width + len(COLORS['water']) + len(RESET)
                ],
                f"{COLORS['sand']}╠{'═' * (width - 2)}╣{RESET}",
                _fit(
                    f"{COLORS['sand']}║{RESET}  output  {self.output_dir}",
                    width - 1,
                )
                + f"{COLORS['sand']}║{RESET}",
                f"{COLORS['sand']}╚{'═' * (width - 2)}╝{RESET}",
            ]
            if len(lines) > height:
                lines = lines[: max(1, height - 1)]
            self._last_lines = len(lines)
            rendered = "\n".join(lines)
            self.stream.write(f"{ESC}H{rendered}{ESC}J")
            self.stream.flush()

    @staticmethod
    def _diversity(population: Sequence[Individual]) -> float:
        if len(population) < 2:
            return 0.0
        dimensions = len(population[0].alleles)
        if not dimensions:
            return 0.0
        totals: list[float] = []
        for first, second in zip(population, population[1:]):
            totals.append(
                math.sqrt(
                    sum(
                        min(abs(a - b) % 360.0, 360.0 - (abs(a - b) % 360.0)) ** 2
                        for a, b in zip(first.alleles, second.alleles)
                    )
                    / dimensions
                )
            )
        return sum(totals) / len(totals)

    def update(
        self,
        stats: GenerationStats,
        islands: Sequence[Sequence[Individual]],
        migrations: Sequence[Mapping[str, Any]] = (),
    ) -> None:
        self.mutation_history.append(stats.mutation_probability)
        self.crossover_history.append(stats.crossover_probability)
        for name in self.objective_names:
            self.objective_history[name].append(
                float(stats.objective_minima.get(name, float("inf")))
            )
        self._write_log(stats, migrations)
        if not self.enabled or self.closed:
            return
        self._latest_frame = (
            stats,
            tuple(tuple(population) for population in islands),
            tuple(dict(event) for event in migrations),
        )
        self._enter_screen()
        if migrations:
            for phase in range(12):
                with self._draw_lock:
                    self._draw(stats, islands, migrations, fleet_phase=phase)
                time.sleep(max(0.0, self.migration_delay))
        with self._draw_lock:
            self._draw(stats, islands, migrations)

    def _write_log(
        self,
        stats: GenerationStats,
        migrations: Sequence[Mapping[str, Any]],
    ) -> None:
        """Keep a clean text log while ANSI frames are drawn on the terminal."""

        objectives = " ".join(
            f"{name}={_format_metric(float(stats.objective_minima.get(name, float('inf'))))}"
            for name in self.objective_names
        )
        line = (
            f"generation={stats.generation} valid={stats.valid} pareto={stats.pareto_size} "
            f"diversity={stats.diversity_deg:.4f} Pmut={stats.mutation_probability:.6f} "
            f"Pcross={stats.crossover_probability:.6f} migrants={len(migrations)} {objectives}\n"
        )
        self.output_dir.mkdir(parents=True, exist_ok=True)
        with self.log_path.open("a", encoding="utf-8") as handle:
            handle.write(line)

    def _draw(
        self,
        stats: GenerationStats,
        islands: Sequence[Sequence[Individual]],
        migrations: Sequence[Mapping[str, Any]],
        fleet_phase: int | None = None,
    ) -> None:
        width, height = shutil.get_terminal_size((120, 38))
        width = max(72, width)
        # Below 100 columns, horizontal resolution is the limiting factor even
        # in a tall window: use the map/viewer interaction instead of stacking
        # several low-resolution molecular cards.
        tiny_terminal = width < 100
        snapshots = self._snapshots(islands, stats)
        if snapshots:
            self._selected_island %= len(snapshots)
        focus_viewer = self._molecule_view_open and bool(snapshots)
        previews_hidden = (
            self._previews_hidden
            if self._previews_hidden is not None
            else tiny_terminal
        )
        overview_mode = not focus_viewer and previews_hidden
        gallery_mode = not focus_viewer and not overview_mode
        molecule_first = focus_viewer or (gallery_mode and width >= 140)
        displayed_snapshots = snapshots
        focus_index: int | None = None
        if focus_viewer:
            focus_index = self._selected_island
            displayed_snapshots = [snapshots[focus_index]]
        progress_width = max(10, min(46, width - 48))
        filled = (
            progress_width
            if self.generations == 0
            else round(progress_width * min(1.0, stats.generation / self.generations))
        )
        bar = "█" * filled + "░" * (progress_width - filled)
        if focus_viewer:
            controls = dashboard_controls(
                "focus",
                selected=focus_index or 0,
                count=len(snapshots),
            )
        elif overview_mode:
            controls = dashboard_controls("overview", compact=tiny_terminal)
        else:
            controls = dashboard_controls("gallery", compact=tiny_terminal)
        if tiny_terminal:
            lines = [
                f"{COLORS['sand']}╔{'═' * (width - 2)}╗{RESET}",
                _fit(
                    f"{COLORS['sand']}║{RESET} SEEKER  g {stats.generation}/{self.generations}  "
                    f"{COLORS['cyan']}{controls}{RESET}",
                    width - 1,
                )
                + f"{COLORS['sand']}║{RESET}",
                f"{COLORS['sand']}╠{'═' * (width - 2)}╣{RESET}",
            ]
        else:
            lines = [
                f"{COLORS['sand']}╔{'═' * (width - 2)}╗{RESET}",
                _fit(
                    f"{COLORS['sand']}║{RESET}  SEEKER  {COLORS['muted']}terminal evolutionary observatory{RESET}"
                    f"  generation {stats.generation}/{self.generations}  "
                    f"{COLORS['cyan']}{controls}{RESET}  {COLORS['cyan']}{bar}{RESET}",
                    width - 1,
                )
                + f"{COLORS['sand']}║{RESET}",
                f"{COLORS['sand']}╠{'═' * (width - 2)}╣{RESET}",
                f"{COLORS['water']}{'  ≋  ' * max(1, width // 5)}{RESET}"[
                    : width + len(COLORS['water']) + len(RESET)
                ],
            ]
        if molecule_first:
            # Full-screen terminals with a large font are wide but often expose
            # only ~32 rows.  Spend those scarce rows on molecular geometry;
            # charts are summarized numerically in the footer instead.
            compact_overhead = (
                14
                if tiny_terminal and focus_viewer and fleet_phase is not None
                else 11
                if tiny_terminal and focus_viewer
                else 17
                if fleet_phase is not None
                else 14
            )
            molecule_height = min(40, max(12, height - compact_overhead))
        else:
            molecule_height = (
                25
                if height >= 46
                else 21
                if height >= 42
                else 15
                if height >= 36
                else 10
                if height >= 32
                else 6
            )
        if overview_mode:
            archipelago = self._overview_lines(
                snapshots,
                width,
                migrations,
                fleet_phase,
            )
        else:
            archipelago = self._archipelago_lines(
                displayed_snapshots,
                width,
                migrations,
                fleet_phase,
                molecule_height,
                compact=molecule_first,
                tiny=tiny_terminal and focus_viewer,
            )
        lines.extend(archipelago)
        if overview_mode:
            # The overview never spends cells on molecular rasters.  Keep the
            # compact histories when they fit, but never hide an island card.
            graph_lines = self._graph_lines(stats, width, 1)
            if len(lines) + 1 + len(graph_lines) + 4 <= height:
                lines.append(f"{COLORS['water']}{'  ≋  ' * max(1, width // 5)}{RESET}")
                lines.extend(graph_lines)
        elif not molecule_first:
            lines.append(f"{COLORS['water']}{'  ≋  ' * max(1, width // 5)}{RESET}")
            graph_groups = 1 + max(1, math.ceil(len(self.objective_names) / 2))
            fixed_lines = len(lines) + 4
            chart_height = max(
                1,
                min(3, max(1, (height - fixed_lines) // graph_groups - 1)),
            )
            lines.extend(self._graph_lines(stats, width, chart_height))
        migration_text = "quiet waters"
        if migrations:
            survived = sum(bool(event.get("survived")) for event in migrations)
            if fleet_phase is None:
                migration_text = (
                    f"fleet migration complete: {survived}/{len(migrations)} settlers survived"
                )
            else:
                migration_text = "MIGRATION IN PROGRESS — flocks crossing the archipelago"
        if molecule_first:
            focus_text = (
                f"focus island {focus_index + 1}/{len(snapshots)}  "
                if focus_index is not None
                else ""
            )
            detail_text = (
                f"Pmut {stats.mutation_probability:.5f}  "
                f"Pcross {stats.crossover_probability:.5f}  "
                + "  ".join(
                    f"{name} {_format_metric(float(stats.objective_minima.get(name, float('inf'))))}"
                    for name in self.objective_names
                )
                + f"  {focus_text}molecule-first  "
            )
        else:
            detail_text = (
                f"charts last {min(len(self.mutation_history), self.history_window)}g  "
            )
        status_text = (
            f"{COLORS['sand']}║{RESET}  valid {stats.valid}  pareto {stats.pareto_size}  "
            f"diversity {stats.diversity_deg:.2f}°  archive {stats.archive_size}  "
            f"{detail_text}{COLORS['yellow']}{migration_text}{RESET}"
        )
        lines.extend(
            [
                f"{COLORS['sand']}╠{'═' * (width - 2)}╣{RESET}",
                _fit(
                    status_text,
                    width - 1,
                ) + f"{COLORS['sand']}║{RESET}",
                _fit(
                    f"{COLORS['sand']}║{RESET}  output  {self.output_dir}", width - 1
                ) + f"{COLORS['sand']}║{RESET}",
                f"{COLORS['sand']}╚{'═' * (width - 2)}╝{RESET}",
            ]
        )
        if len(lines) > height:
            # Keep the operational footer visible on short terminals.  Island
            # ornamentation and charts may grow, but status/output information
            # must never disappear below the viewport.
            available = max(1, height - 1)
            footer_size = min(4, available)
            lines = lines[: available - footer_size] + lines[-footer_size:]
        payload = "\n".join(lines)
        self._last_lines = len(lines)
        self.stream.write(f"{ESC}H{payload}{ESC}J")
        self.stream.flush()

    def _overview_lines(
        self,
        snapshots: Sequence[IslandSnapshot],
        width: int,
        migrations: Sequence[Mapping[str, Any]],
        fleet_phase: int | None,
    ) -> list[str]:
        """Render every island as a small map card without building geometry."""

        if not snapshots:
            return ["No islands have reported yet."]
        # Use the full horizontal extent in compact mode.  Keeping this at two
        # columns left otherwise small fleets below the viewport on wide but
        # short terminals—the exact case compact mode is meant to solve.
        minimum_card_width = 34 if width < 100 else 48
        gap = 2
        columns = max(
            1,
            min(
                len(snapshots),
                (width - 2 + gap) // (minimum_card_width + gap),
            ),
        )
        gap = gap if columns > 1 else 0
        card_width = max(34, (width - gap * (columns - 1) - 2) // columns)
        routes = {
            (int(event.get("source_island", -1)), int(event.get("destination_island", -1)))
            for event in migrations
        }
        lines: list[str] = []
        for row_start in range(0, len(snapshots), columns):
            row = snapshots[row_start : row_start + columns]
            if fleet_phase is not None and routes:
                lines.extend(
                    self._migration_sky(
                        row,
                        row_start,
                        card_width,
                        width,
                        routes,
                        fleet_phase,
                        12,
                    )
                )
            cards: list[list[str]] = []
            for item in row:
                inner_width = card_width - 8
                selected = item.index == self._selected_island
                marker = "▶" if selected else " "
                compromise = (
                    f"#{item.compromise.id} d={item.compromise_score:.3f}"
                    if item.compromise is not None
                    else "n/a"
                )
                cap_width = max(8, card_width - 12)
                cap = "▁▂▄" + "▀" * max(2, cap_width - 6) + "▄▂▁"
                top = (
                    f"{COLORS['water']}≈{RESET} "
                    + f"{COLORS['muted']}▝▀▘{RESET} "
                    + f"{COLORS['sand']}{cap}{RESET} "
                    + f"{COLORS['muted']}▝▀▘{RESET}"
                )
                title = (
                    f"{COLORS['water']}≈{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['sand']}▒▓{RESET}"
                    + _fit(
                        f"{marker} {COLORS['green']}ISLAND {item.index + 1}{RESET} "
                        f"{COLORS['cyan']}3D BALL·STICK{RESET}  BAL {compromise}",
                        inner_width,
                    )
                    + f"{COLORS['sand']}▓▒{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['water']}≈{RESET}"
                )
                metrics_text = (
                    f"fitness {_format_metric(item.fitness)}  "
                    f"diversity {item.diversity:.1f}°"
                )
                metrics = (
                    f"{COLORS['water']}≈{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['sand']}▒▓{RESET}"
                    + _fit(metrics_text, inner_width)
                    + f"{COLORS['sand']}▓▒{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['water']}≈{RESET}"
                )
                population_text = (
                    f"pareto {item.pareto}/{item.valid}  "
                    f"valid {item.valid}/{item.size}  population {item.size}"
                )
                population = (
                    f"{COLORS['water']}≈{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['sand']}▒▓{RESET}"
                    + _fit(population_text, inner_width)
                    + f"{COLORS['sand']}▓▒{RESET}{COLORS['dim_sand']}░{RESET}"
                    f"{COLORS['water']}≈{RESET}"
                )
                cards.append(
                    [
                        _fit(top, card_width),
                        _fit(title, card_width),
                        _fit(metrics, card_width),
                        _fit(population, card_width),
                    ]
                )
            for line_index in range(4):
                combined = "  ".join(card[line_index] for card in cards)
                visible = _visible_len(combined)
                lines.append(" " * max(0, (width - visible) // 2) + combined)
        return lines

    def _archipelago_lines(
        self,
        snapshots: Sequence[IslandSnapshot],
        width: int,
        migrations: Sequence[Mapping[str, Any]],
        fleet_phase: int | None,
        molecule_height: int = 8,
        *,
        compact: bool = False,
        tiny: bool = False,
    ) -> list[str]:
        if not snapshots:
            return ["No islands have reported yet."]
        minimum_card_width = 48
        columns = max(
            1,
            min(len(snapshots), width // (minimum_card_width + 2)),
        )
        card_width = (
            width
            if tiny
            else min(
                96,
                max(
                    minimum_card_width,
                    (width - 2 * max(0, columns - 1) - 2) // columns,
                ),
            )
        )
        molecule_height = max(4, int(molecule_height))
        lines: list[str] = []
        routes = {
            (int(event.get("source_island", -1)), int(event.get("destination_island", -1)))
            for event in migrations
        }
        for row_start in range(0, len(snapshots), columns):
            row = snapshots[row_start : row_start + columns]
            if fleet_phase is not None and routes:
                lines.extend(
                    self._migration_sky(
                        row,
                        row_start,
                        card_width,
                        width,
                        routes,
                        fleet_phase,
                        12,
                    )
                )
            cards: list[list[str]] = []
            for item in row:
                inner_width = card_width - 8
                preview_width = max(1, inner_width - 4)
                if item.compromise is None:
                    preview = [
                        _fit(
                            f"{COLORS['muted']}geometry unavailable{RESET}",
                            preview_width,
                        )
                    ] + [
                        " " * preview_width
                        for _line in range(molecule_height - 1)
                    ]
                    compromise_label = "BAL n/a"
                else:
                    compromise_label = (
                        f"BAL #{item.compromise.id} d={item.compromise_score:.3f}"
                    )
                    try:
                        molecule = (
                            self.molecule_provider(item.compromise)
                            if self.molecule_provider is not None
                            else None
                        )
                        preview = (
                            render_molecule(
                                molecule,
                                preview_width,
                                molecule_height,
                                angle_degrees=18.0,
                            )
                            if molecule is not None
                            else [
                                _fit(
                                    f"{COLORS['muted']}covalent map unavailable{RESET}",
                                    preview_width,
                                )
                            ]
                            + [
                                " " * preview_width
                                for _line in range(molecule_height - 1)
                            ]
                        )
                    except Exception:
                        preview = [
                            _fit(
                                f"{COLORS['muted']}geometry unavailable{RESET}",
                                preview_width,
                            )
                        ] + [
                            " " * preview_width
                            for _line in range(molecule_height - 1)
                        ]

                def body(value: str, inset: int = 0, *, rocky: bool = False) -> str:
                    inset = min(max(0, inset), max(0, (inner_width - 1) // 2))
                    content_width = inner_width - 2 * inset
                    left_edge = (
                        f"{COLORS['water']}≈{RESET}"
                        f"{COLORS['dim_sand']}░{RESET}"
                        f"{COLORS['sand']}▒{RESET}"
                        f"{COLORS['muted']}▟{RESET}"
                        if rocky
                        else f"{COLORS['water']}≈{RESET}"
                        f"{COLORS['dim_sand']}░{RESET}"
                        f"{COLORS['sand']}▒▓{RESET}"
                    )
                    right_edge = (
                        f"{COLORS['muted']}▙{RESET}"
                        f"{COLORS['sand']}▒{RESET}"
                        f"{COLORS['dim_sand']}░{RESET}"
                        f"{COLORS['water']}≈{RESET}"
                        if rocky
                        else f"{COLORS['sand']}▓▒{RESET}"
                        f"{COLORS['dim_sand']}░{RESET}"
                        f"{COLORS['water']}≈{RESET}"
                    )
                    return (
                        " " * inset
                        + left_edge
                        + _fit(value, content_width)
                        + right_edge
                        + " " * inset
                    )

                def colored_line(cells: Sequence[tuple[str, str]]) -> str:
                    pieces: list[str] = []
                    active_color = ""
                    for glyph, color in cells:
                        if color != active_color:
                            if active_color:
                                pieces.append(RESET)
                            if color:
                                pieces.append(COLORS[color])
                            active_color = color
                        pieces.append(glyph)
                    if active_color:
                        pieces.append(RESET)
                    return "".join(pieces)

                def art_line(
                    stamps: Sequence[tuple[int, str, str]],
                ) -> str:
                    canvas = [(" ", "") for _column in range(card_width)]
                    for center, value, color in stamps:
                        start = center - len(value) // 2
                        for offset, glyph in enumerate(value):
                            column = start + offset
                            if 0 <= column < card_width and glyph != " ":
                                canvas[column] = (glyph, color)
                    return colored_line(canvas)

                shoulder = body(
                    _fit(
                        f" {COLORS['green']}ISLAND {item.index + 1}{RESET}  "
                        f"{COLORS['cyan']}3D BALL·STICK{RESET}  {compromise_label}",
                        preview_width,
                    ),
                    2,
                )
                coast_width = max(12, card_width - 14)
                rock_centers = (
                    card_width // 6,
                    card_width // 2,
                    5 * card_width // 6,
                )
                lower_inset = 4
                lower_width = inner_width - 2 * lower_inset
                lower_cells = [(" ", "") for _column in range(card_width)]
                lower_start = lower_inset
                lower_shore = (
                    ("≈", "water"),
                    ("░", "dim_sand"),
                    ("▒", "sand"),
                    ("▓", "sand"),
                    *(("▀", "sand") for _column in range(lower_width)),
                    ("▓", "sand"),
                    ("▒", "sand"),
                    ("░", "dim_sand"),
                    ("≈", "water"),
                )
                lower_cells[lower_start : lower_start + len(lower_shore)] = lower_shore
                for fraction in (0.18, 0.48, 0.77):
                    rock_start = lower_start + 4 + round(fraction * (lower_width - 3))
                    lower_cells[rock_start : rock_start + 3] = (
                        ("▟", "muted"),
                        ("█", "muted"),
                        ("▙", "muted"),
                    )
                lower_coast = colored_line(lower_cells)
                rock_caps = art_line(
                    [
                        (center, "▗▄▖", "muted")
                        for center in rock_centers
                    ]
                )
                top_coast = art_line(
                    [
                        (
                            card_width // 2,
                            "▁▂▄" + "▀" * (coast_width - 6) + "▄▂▁",
                            "sand",
                        ),
                        *((center, "▝▀▘", "dim_sand") for center in rock_centers),
                    ]
                )
                waterline = art_line(
                    [
                        (card_width // 6, "≋  ≋", "water"),
                        (card_width // 2, "≋   ≋   ≋", "water"),
                        (5 * card_width // 6, "≋  ≋", "water"),
                    ]
                )

                preview_lines = [
                    body(
                        line,
                        2
                        if line_index in (0, len(preview) - 1)
                        else 1
                        if line_index in (1, len(preview) - 2)
                        else 0,
                        rocky=(line_index + item.index) % 4 == 1,
                    )
                    for line_index, line in enumerate(preview)
                ]
                if tiny:
                    card_lines = [
                        shoulder,
                        *preview_lines,
                        body(
                            f" fit {_format_metric(item.fitness)}"
                            f"  div {item.diversity:.1f}°"
                            f"  pareto {item.pareto}/{item.valid}"
                            f"  population {item.size}",
                            1,
                            rocky=True,
                        ),
                        lower_coast,
                    ]
                else:
                    card_lines = (
                        ([rock_caps] if not compact else [])
                        + [
                        top_coast,
                        shoulder,
                        *preview_lines,
                        body(
                            f" fitness {_format_metric(item.fitness):>10}"
                            f"   diversity {item.diversity:>6.1f}°",
                            1,
                            rocky=True,
                        ),
                        body(
                            f" pareto {item.pareto}/{item.valid}"
                            f"   valid {item.valid}/{item.size}"
                            f"   population {item.size}",
                            2,
                        ),
                        lower_coast,
                        ]
                        + ([waterline] if not compact else [])
                    )
                cards.append(card_lines)
            for line_index in range(len(cards[0])):
                combined = "  ".join(_fit(card[line_index], card_width) for card in cards)
                lines.append(combined.center(width + (len(combined) - _visible_len(combined))))
        return lines

    @staticmethod
    def _migration_sky(
        row: Sequence[IslandSnapshot],
        row_start: int,
        card_width: int,
        width: int,
        routes: set[tuple[int, int]],
        phase: int,
        phases: int,
    ) -> list[str]:
        """Animate several visible flocks along the actual island routes."""

        block_width = len(row) * card_width + max(0, len(row) - 1) * 2
        left_margin = max(0, (width - block_width) // 2)
        centers = {
            item.index: left_margin
            + local_index * (card_width + 2)
            + card_width // 2
            for local_index, item in enumerate(row)
        }
        sky = [[" " for _column in range(width)] for _line in range(3)]
        fraction = phase / max(1, phases - 1)
        for route_index, (source, destination) in enumerate(sorted(routes)):
            if source not in centers or destination not in centers:
                continue
            start, end = centers[source], centers[destination]
            direction = 1 if end >= start else -1
            span = abs(end - start)
            for trail_x in range(min(start, end) + 3, max(start, end) - 2, 3):
                sky[2][trail_x] = "·"
            center = round(start + (end - start) * fraction)
            flight_row = 2 - round(2 * math.sin(math.pi * fraction))
            flock = "»˅✦˅»" if direction > 0 else "«˅✦˅«"
            # Offset simultaneous flocks slightly so ring migrations look like
            # independent swarms instead of one overwritten marker.
            flight_row = min(2, max(0, flight_row + (route_index % 2)))
            begin = center - len(flock) // 2
            for offset, glyph in enumerate(flock):
                column = begin + offset
                if 0 <= column < width:
                    sky[flight_row][column] = glyph
            wing_row = max(0, flight_row - 1)
            for column in (center - 4, center + 4):
                if 0 <= column < width:
                    sky[wing_row][column] = "˄"
            if span > 20:
                for column in (center - 7, center + 7):
                    if 0 <= column < width:
                        sky[min(2, flight_row + 1)][column] = "˅"
        return [
            f"{COLORS['yellow']}{''.join(line)}{RESET}" for line in sky
        ]

    def _graph_lines(
        self,
        stats: GenerationStats,
        width: int,
        chart_height: int = 3,
    ) -> list[str]:
        panel_width = max(28, width // 2 - 3)
        chart_width = max(12, panel_width - 4)

        def pair_lines(
            left_name: str,
            left_values: Sequence[float],
            left_value: float,
            left_color: str,
            right_name: str | None = None,
            right_values: Sequence[float] = (),
            right_value: float = float("inf"),
            right_color: str = "orange",
        ) -> list[str]:
            left_label = (
                f"{COLORS[left_color]}{left_name:<18}{RESET}"
                f"{_format_metric(left_value):>{max(8, panel_width - 18)}}"
            )
            right_label = ""
            if right_name is not None:
                right_label = (
                    f"{COLORS[right_color]}{right_name:<18}{RESET}"
                    f"{_format_metric(right_value):>{max(8, panel_width - 18)}}"
                )
            result = ["  " + _fit(left_label, panel_width) + "  " + right_label]
            left_chart = vertical_chart(
                self._recent_history(left_values), chart_width, chart_height
            )
            right_chart = (
                vertical_chart(
                    self._recent_history(right_values), chart_width, chart_height
                )
                if right_name is not None
                else ["" for _row in range(chart_height)]
            )
            for left_row, right_row in zip(left_chart, right_chart):
                left_plot = f"{COLORS[left_color]}│ {left_row}{RESET}"
                right_plot = (
                    f"{COLORS[right_color]}│ {right_row}{RESET}"
                    if right_name is not None
                    else ""
                )
                result.append("  " + _fit(left_plot, panel_width) + "  " + right_plot)
            return result

        lines = pair_lines(
            "Pmut",
            self.mutation_history,
            stats.mutation_probability,
            "cyan",
            "Pcross",
            self.crossover_history,
            stats.crossover_probability,
            "green",
        )
        for index in range(0, len(self.objective_names), 2):
            left_name = self.objective_names[index]
            left_values = self.objective_history[left_name]
            left_current = next(
                (value for value in reversed(left_values) if math.isfinite(value)),
                float("inf"),
            )
            right_name = (
                self.objective_names[index + 1]
                if index + 1 < len(self.objective_names)
                else None
            )
            right_values = self.objective_history[right_name] if right_name else ()
            right_current = next(
                (value for value in reversed(right_values) if math.isfinite(value)),
                float("inf"),
            )
            lines.extend(
                pair_lines(
                    left_name,
                    left_values,
                    left_current,
                    "orange",
                    right_name,
                    right_values,
                    right_current,
                    "orange",
                )
            )
        return lines

    def close(self, message: str = "Evolution dashboard closed; textual output resumed.") -> None:
        if self.closed:
            return
        self.closed = True
        self._stop_input_listener()
        if self.started:
            self.stream.write(f"{ESC}?25h{ESC}?1049l")
            self.stream.write(message + "\n")
            self.stream.flush()

    def __enter__(self) -> "TerminalDashboard":
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None:
        self.close("Evolution dashboard closed." if exc is None else "Evolution dashboard interrupted.")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="SEEKER ANSI terminal artwork")
    parser.add_argument("--intro", action="store_true", help="play the startup animation")
    parser.add_argument("--no-delay", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    if args.intro:
        play_intro(frame_delay=0.0 if args.no_delay else 0.09)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
